// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressservice.proto

package protocol

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Pin                  string   `protobuf:"bytes,6,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Person) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Person) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Person) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type PersonID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonID) Reset()         { *m = PersonID{} }
func (m *PersonID) String() string { return proto.CompactTextString(m) }
func (*PersonID) ProtoMessage()    {}
func (*PersonID) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{1}
}

func (m *PersonID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonID.Unmarshal(m, b)
}
func (m *PersonID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonID.Marshal(b, m, deterministic)
}
func (m *PersonID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonID.Merge(m, src)
}
func (m *PersonID) XXX_Size() int {
	return xxx_messageInfo_PersonID.Size(m)
}
func (m *PersonID) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonID.DiscardUnknown(m)
}

var xxx_messageInfo_PersonID proto.InternalMessageInfo

func (m *PersonID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PersonList struct {
	PersonsList          []*Person `protobuf:"bytes,1,rep,name=personsList,proto3" json:"personsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PersonList) Reset()         { *m = PersonList{} }
func (m *PersonList) String() string { return proto.CompactTextString(m) }
func (*PersonList) ProtoMessage()    {}
func (*PersonList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{2}
}

func (m *PersonList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonList.Unmarshal(m, b)
}
func (m *PersonList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonList.Marshal(b, m, deterministic)
}
func (m *PersonList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonList.Merge(m, src)
}
func (m *PersonList) XXX_Size() int {
	return xxx_messageInfo_PersonList.Size(m)
}
func (m *PersonList) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonList.DiscardUnknown(m)
}

var xxx_messageInfo_PersonList proto.InternalMessageInfo

func (m *PersonList) GetPersonsList() []*Person {
	if m != nil {
		return m.PersonsList
	}
	return nil
}

type ServiceResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceResponse) Reset()         { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()    {}
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{3}
}

func (m *ServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResponse.Unmarshal(m, b)
}
func (m *ServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResponse.Marshal(b, m, deterministic)
}
func (m *ServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResponse.Merge(m, src)
}
func (m *ServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceResponse.Size(m)
}
func (m *ServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResponse proto.InternalMessageInfo

func (m *ServiceResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *ServiceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ModifyPerson struct {
	Id                   *PersonID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModifiedPerson       *Person   `protobuf:"bytes,2,opt,name=modifiedPerson,proto3" json:"modifiedPerson,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ModifyPerson) Reset()         { *m = ModifyPerson{} }
func (m *ModifyPerson) String() string { return proto.CompactTextString(m) }
func (*ModifyPerson) ProtoMessage()    {}
func (*ModifyPerson) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{4}
}

func (m *ModifyPerson) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyPerson.Unmarshal(m, b)
}
func (m *ModifyPerson) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyPerson.Marshal(b, m, deterministic)
}
func (m *ModifyPerson) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyPerson.Merge(m, src)
}
func (m *ModifyPerson) XXX_Size() int {
	return xxx_messageInfo_ModifyPerson.Size(m)
}
func (m *ModifyPerson) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyPerson.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyPerson proto.InternalMessageInfo

func (m *ModifyPerson) GetId() *PersonID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ModifyPerson) GetModifiedPerson() *Person {
	if m != nil {
		return m.ModifiedPerson
	}
	return nil
}

type EmptyParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParams) Reset()         { *m = EmptyParams{} }
func (m *EmptyParams) String() string { return proto.CompactTextString(m) }
func (*EmptyParams) ProtoMessage()    {}
func (*EmptyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{5}
}

func (m *EmptyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParams.Unmarshal(m, b)
}
func (m *EmptyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParams.Marshal(b, m, deterministic)
}
func (m *EmptyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParams.Merge(m, src)
}
func (m *EmptyParams) XXX_Size() int {
	return xxx_messageInfo_EmptyParams.Size(m)
}
func (m *EmptyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParams.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParams proto.InternalMessageInfo

type EventStore struct {
	Activity             string   `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	ActivityStatus       bool     `protobuf:"varint,2,opt,name=activity_status,json=activityStatus,proto3" json:"activity_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStore) Reset()         { *m = EventStore{} }
func (m *EventStore) String() string { return proto.CompactTextString(m) }
func (*EventStore) ProtoMessage()    {}
func (*EventStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2fd2802e487b199, []int{6}
}

func (m *EventStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStore.Unmarshal(m, b)
}
func (m *EventStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStore.Marshal(b, m, deterministic)
}
func (m *EventStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStore.Merge(m, src)
}
func (m *EventStore) XXX_Size() int {
	return xxx_messageInfo_EventStore.Size(m)
}
func (m *EventStore) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStore.DiscardUnknown(m)
}

var xxx_messageInfo_EventStore proto.InternalMessageInfo

func (m *EventStore) GetActivity() string {
	if m != nil {
		return m.Activity
	}
	return ""
}

func (m *EventStore) GetActivityStatus() bool {
	if m != nil {
		return m.ActivityStatus
	}
	return false
}

func init() {
	proto.RegisterType((*Person)(nil), "protocol.Person")
	proto.RegisterType((*PersonID)(nil), "protocol.PersonID")
	proto.RegisterType((*PersonList)(nil), "protocol.PersonList")
	proto.RegisterType((*ServiceResponse)(nil), "protocol.ServiceResponse")
	proto.RegisterType((*ModifyPerson)(nil), "protocol.ModifyPerson")
	proto.RegisterType((*EmptyParams)(nil), "protocol.EmptyParams")
	proto.RegisterType((*EventStore)(nil), "protocol.EventStore")
}

func init() {
	proto.RegisterFile("addressservice.proto", fileDescriptor_a2fd2802e487b199)
}

var fileDescriptor_a2fd2802e487b199 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x6a, 0xdb, 0x40,
	0x10, 0xad, 0xac, 0x44, 0x51, 0x46, 0xad, 0x12, 0x06, 0xb7, 0xa8, 0x86, 0x42, 0xd9, 0x4b, 0x73,
	0xf2, 0x41, 0xed, 0x21, 0x3d, 0x14, 0x1a, 0x70, 0x0a, 0x81, 0x16, 0x52, 0xe9, 0x03, 0x82, 0x2a,
	0x4d, 0xc9, 0x82, 0xa4, 0x15, 0xbb, 0x1b, 0x83, 0xaf, 0xfd, 0xa2, 0x7e, 0x62, 0xb5, 0xbb, 0x92,
	0x6d, 0x54, 0xc7, 0x27, 0xcd, 0x3c, 0xbd, 0x99, 0x79, 0xef, 0x2d, 0xcc, 0x8b, 0xaa, 0x92, 0xa4,
	0x94, 0x22, 0xb9, 0xe6, 0x25, 0x2d, 0x3b, 0x29, 0xb4, 0xc0, 0xd0, 0x7e, 0x4a, 0x51, 0xb3, 0x3f,
	0x1e, 0x04, 0xf7, 0x24, 0x95, 0x68, 0x11, 0xe1, 0xa4, 0x2d, 0x1a, 0x4a, 0xbc, 0xf7, 0xde, 0xd5,
	0x79, 0x66, 0x6b, 0x8c, 0x61, 0xc6, 0xab, 0x64, 0x66, 0x91, 0xbe, 0xc2, 0x39, 0x9c, 0x76, 0x8f,
	0xa2, 0xa5, 0xc4, 0xb7, 0x90, 0x6b, 0x30, 0x81, 0xb3, 0xe1, 0x4c, 0x72, 0x62, 0xf1, 0xb1, 0x35,
	0x3b, 0x4b, 0xae, 0x37, 0xc9, 0xa9, 0xdb, 0x69, 0x6a, 0xbc, 0x04, 0xbf, 0xe3, 0x6d, 0x12, 0x58,
	0xc8, 0x94, 0x6c, 0x01, 0xa1, 0xd3, 0x70, 0xb7, 0x1a, 0x2e, 0x7a, 0xe3, 0x45, 0xf6, 0x15, 0xc0,
	0xfd, 0xfb, 0xce, 0x95, 0xc6, 0x14, 0xa2, 0xce, 0x76, 0xca, 0xb4, 0x3d, 0xcd, 0xbf, 0x8a, 0xd2,
	0xcb, 0xe5, 0x68, 0x67, 0xe9, 0xa8, 0xd9, 0x3e, 0x89, 0x7d, 0x83, 0x8b, 0xdc, 0xb9, 0xcf, 0x48,
	0x75, 0x3d, 0x4a, 0xf8, 0x0e, 0x80, 0xab, 0x07, 0xf5, 0x54, 0x96, 0x46, 0xb3, 0x39, 0x16, 0x66,
	0xe7, 0x5c, 0xe5, 0x0e, 0x30, 0x2e, 0x49, 0x4a, 0x21, 0x07, 0xe3, 0xae, 0x61, 0x35, 0xbc, 0xfc,
	0x21, 0x2a, 0xfe, 0x7b, 0x33, 0xe4, 0xc5, 0xb6, 0x4a, 0xa3, 0x14, 0xa7, 0x12, 0xee, 0x56, 0x36,
	0xaf, 0x6b, 0x88, 0x1b, 0x33, 0xc3, 0xa9, 0x72, 0xb8, 0x5d, 0x79, 0x48, 0xf2, 0x84, 0xc7, 0x5e,
	0x41, 0x74, 0xdb, 0x74, 0x7a, 0x73, 0x5f, 0xc8, 0xa2, 0x51, 0xec, 0x27, 0xc0, 0xed, 0x9a, 0x5a,
	0x9d, 0x6b, 0x21, 0x09, 0xfb, 0xc0, 0x8a, 0x52, 0xf3, 0xb5, 0x89, 0xd6, 0x45, 0xb5, 0xed, 0xf1,
	0x03, 0x5c, 0x8c, 0xf5, 0x83, 0xd2, 0x85, 0x7e, 0x52, 0xf6, 0x66, 0x98, 0xc5, 0x23, 0x9c, 0x5b,
	0x34, 0xfd, 0x3b, 0x83, 0xf8, 0xc6, 0xbd, 0xd3, 0x90, 0x0f, 0x7e, 0x82, 0x20, 0xa7, 0x42, 0x96,
	0x8f, 0x78, 0xc0, 0xd0, 0x62, 0x3e, 0xc5, 0x6c, 0xbc, 0x2f, 0xfa, 0x29, 0xbf, 0xdf, 0x83, 0xff,
	0x79, 0x5a, 0xbc, 0xdd, 0x21, 0x93, 0x17, 0xe8, 0xa7, 0xbe, 0x40, 0xe0, 0xe2, 0xc4, 0x37, 0x3b,
	0xda, 0x7e, 0xc0, 0xc7, 0xc7, 0x3f, 0x43, 0xb0, 0xa2, 0x9a, 0x34, 0x1d, 0x94, 0x7a, 0x74, 0xf4,
	0x1a, 0xce, 0x8c, 0xf2, 0x9b, 0xba, 0xc6, 0xd7, 0x3b, 0xde, 0x5e, 0xda, 0xcf, 0x39, 0xfd, 0x15,
	0x58, 0xf8, 0xe3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x8a, 0xd7, 0x59, 0x56, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddressServiceClient is the client API for AddressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddressServiceClient interface {
	Search(ctx context.Context, in *PersonID, opts ...grpc.CallOption) (*PersonList, error)
	Add(ctx context.Context, in *Person, opts ...grpc.CallOption) (*ServiceResponse, error)
	Modify(ctx context.Context, in *ModifyPerson, opts ...grpc.CallOption) (*ServiceResponse, error)
	Delete(ctx context.Context, in *PersonID, opts ...grpc.CallOption) (*ServiceResponse, error)
	ListAll(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*PersonList, error)
}

type addressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddressServiceClient(cc grpc.ClientConnInterface) AddressServiceClient {
	return &addressServiceClient{cc}
}

func (c *addressServiceClient) Search(ctx context.Context, in *PersonID, opts ...grpc.CallOption) (*PersonList, error) {
	out := new(PersonList)
	err := c.cc.Invoke(ctx, "/protocol.AddressService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) Add(ctx context.Context, in *Person, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/protocol.AddressService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) Modify(ctx context.Context, in *ModifyPerson, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/protocol.AddressService/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) Delete(ctx context.Context, in *PersonID, opts ...grpc.CallOption) (*ServiceResponse, error) {
	out := new(ServiceResponse)
	err := c.cc.Invoke(ctx, "/protocol.AddressService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addressServiceClient) ListAll(ctx context.Context, in *EmptyParams, opts ...grpc.CallOption) (*PersonList, error) {
	out := new(PersonList)
	err := c.cc.Invoke(ctx, "/protocol.AddressService/ListAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddressServiceServer is the server API for AddressService service.
type AddressServiceServer interface {
	Search(context.Context, *PersonID) (*PersonList, error)
	Add(context.Context, *Person) (*ServiceResponse, error)
	Modify(context.Context, *ModifyPerson) (*ServiceResponse, error)
	Delete(context.Context, *PersonID) (*ServiceResponse, error)
	ListAll(context.Context, *EmptyParams) (*PersonList, error)
}

// UnimplementedAddressServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddressServiceServer struct {
}

func (*UnimplementedAddressServiceServer) Search(ctx context.Context, req *PersonID) (*PersonList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedAddressServiceServer) Add(ctx context.Context, req *Person) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedAddressServiceServer) Modify(ctx context.Context, req *ModifyPerson) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedAddressServiceServer) Delete(ctx context.Context, req *PersonID) (*ServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedAddressServiceServer) ListAll(ctx context.Context, req *EmptyParams) (*PersonList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAll not implemented")
}

func RegisterAddressServiceServer(s *grpc.Server, srv AddressServiceServer) {
	s.RegisterService(&_AddressService_serviceDesc, srv)
}

func _AddressService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AddressService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).Search(ctx, req.(*PersonID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AddressService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).Add(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyPerson)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AddressService/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).Modify(ctx, req.(*ModifyPerson))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AddressService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).Delete(ctx, req.(*PersonID))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddressService_ListAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddressServiceServer).ListAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.AddressService/ListAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddressServiceServer).ListAll(ctx, req.(*EmptyParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddressService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.AddressService",
	HandlerType: (*AddressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _AddressService_Search_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _AddressService_Add_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _AddressService_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AddressService_Delete_Handler,
		},
		{
			MethodName: "ListAll",
			Handler:    _AddressService_ListAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addressservice.proto",
}
